# Generated by Django 3.2.4 on 2021-06-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('capaciodad', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('moneda', models.CharField(max_length=20)),
                ('caracteristicas', models.CharField(max_length=1500)),
                ('url_img', models.CharField(max_length=100)),
                ('url_catalogo', models.CharField(max_length=100)),
                ('supercategoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=5)),
                ('cp', models.CharField(max_length=5)),
                ('numero_telefonico', models.CharField(max_length=10)),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.estado')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.producto')),
            ],
        ),
    ]
