# Generated by Django 3.2.4 on 2021-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20210702_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.IntegerField()),
                ('producto', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='url_imagen_categoria',
            field=models.CharField(default='alga/asas', max_length=1000),
            preserve_default=False,
        ),
    ]
