# Generated by Django 3.2.4 on 2021-07-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_auto_20210705_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='url_imagen_categoria',
        ),
    ]
