# Generated by Django 3.2.4 on 2021-07-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_auto_20210705_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(max_length=200),
        ),
    ]
