# Generated by Django 3.2.4 on 2021-07-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_alter_producto_moneda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moneda',
        ),
    ]
