# Generated by Django 3.2.4 on 2021-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_auto_20210705_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(),
        ),
    ]
